### PR TITLE
Add tuple method

### PR DESCRIPTION
**Pull request by Leont**
This adds a `tuple` method to retrieved the numbers used for comparison purposes with other version objects.

### CODE REVIEW

**Comment by haarg** [comment]
from_tuple should probably verify that it is receiving only positive integers.

**Comment by Leont** [comment]
> from_tuple should probably verify that it is receiving only positive integers.

True. And TBH I'm not entirely sure I got the semantics right. Should I split it up into decimal versus dotted? Should it always do dotted?

**Comment by haarg** [comment]
I think always doing dotted is fine.

**Comment by Leont** [comment]
This was merged in 0.9932

**Pull request closed without merging**
